import { getWorkspaceDb } from "@/server/tenant/context";

export type ShoppingListEntry = {
  id: string;
  label: string;
  quantity: number | null;
  unit: string | null;
  autoGenerated: boolean;
};

export async function getShoppingListItems(): Promise<ShoppingListEntry[]> {
  const db = await getWorkspaceDb();
  const items = await db.shoppingListItem.findMany({
    where: { done: false },
    orderBy: [{ autoGenerated: "desc" }, { createdAt: "asc" }],
  });

  return items.map((i) => ({
    id: i.id,
    label: i.label,
    quantity: i.quantity,
    unit: i.unit,
    autoGenerated: i.autoGenerated,
  }));
}
