import { beforeEach, describe, expect, it, vi } from "vitest";
import { resetDb, testDb, createWorkspace } from "@/test/db";
import { scopedDb } from "@/server/tenant/extension";

vi.mock("next/cache", () => ({ revalidatePath: vi.fn() }));

const context = { workspaceId: "", userId: "", canWrite: true };

vi.mock("@/server/tenant/context", () => ({
  getScopedDb: async () => ({
    db: scopedDb(context.workspaceId),
    workspaceId: context.workspaceId,
    userId: context.userId,
    role: "OWNER",
    canWrite: context.canWrite,
  }),
  getWorkspaceDb: async () => scopedDb(context.workspaceId),
  assertCanWrite: async () => {
    if (!context.canWrite) throw new Error("Este workspace está em modo somente leitura.");
  },
}));

const { generateAutoShoppingList, toggleShoppingListItem } = await import("./shopping-list");

describe("generateAutoShoppingList", () => {
  beforeEach(async () => {
    await resetDb();
    context.canWrite = true;
  });

  it("cria um item por ingrediente abaixo do mínimo, com o déficit certo", async () => {
    const workspace = await createWorkspace("Confeitaria");
    context.workspaceId = workspace.id;

    const ingredient = await testDb.ingredient.create({
      data: { name: "Açúcar", baseUnit: "G", minStock: 1000, workspaceId: workspace.id },
    });
    const supplier = await testDb.supplier.create({
      data: { name: "Atacadão", workspaceId: workspace.id },
    });
    const purchase = await testDb.purchase.create({
      data: { supplierId: supplier.id, workspaceId: workspace.id },
    });
    await testDb.purchaseItem.create({
      data: {
        ingredientId: ingredient.id,
        purchaseId: purchase.id,
        workspaceId: workspace.id,
        quantity: 400,
        unit: "G",
        pricePaidCents: 800,
      },
    });

    const res = await generateAutoShoppingList();

    expect(res).toEqual({ ok: true, data: { created: 1, updated: 0 } });
    const items = await testDb.shoppingListItem.findMany({ where: { workspaceId: workspace.id } });
    expect(items).toHaveLength(1);
    expect(items[0]).toMatchObject({
      ingredientId: ingredient.id,
      label: "Açúcar",
      quantity: 600,
      unit: "G",
      autoGenerated: true,
      done: false,
    });
  });

  it("na segunda chamada atualiza o item existente em vez de duplicar", async () => {
    const workspace = await createWorkspace("Confeitaria 2");
    context.workspaceId = workspace.id;

    const ingredient = await testDb.ingredient.create({
      data: { name: "Farinha", baseUnit: "G", minStock: 1000, workspaceId: workspace.id },
    });
    const supplier = await testDb.supplier.create({
      data: { name: "Atacadão", workspaceId: workspace.id },
    });
    const purchase = await testDb.purchase.create({
      data: { supplierId: supplier.id, workspaceId: workspace.id },
    });
    await testDb.purchaseItem.create({
      data: {
        ingredientId: ingredient.id, purchaseId: purchase.id, workspaceId: workspace.id,
        quantity: 200, unit: "G", pricePaidCents: 400,
      },
    });

    await generateAutoShoppingList();
    const res = await generateAutoShoppingList();

    expect(res).toEqual({ ok: true, data: { created: 0, updated: 1 } });
    expect(await testDb.shoppingListItem.count({ where: { workspaceId: workspace.id } })).toBe(1);
  });

  it("recusa gerar a lista com o workspace em modo somente leitura", async () => {
    const workspace = await createWorkspace("Confeitaria 3");
    context.workspaceId = workspace.id;
    context.canWrite = false;

    const res = await generateAutoShoppingList();
    expect(res.ok).toBe(false);
  });
});

describe("toggleShoppingListItem", () => {
  beforeEach(async () => {
    await resetDb();
    context.canWrite = true;
  });

  it("marca um item como comprado", async () => {
    const workspace = await createWorkspace("Confeitaria 4");
    context.workspaceId = workspace.id;
    const item = await testDb.shoppingListItem.create({
      data: { workspaceId: workspace.id, label: "Manteiga", autoGenerated: false },
    });

    const res = await toggleShoppingListItem(item.id, true);

    expect(res).toEqual({ ok: true });
    const updated = await testDb.shoppingListItem.findUnique({ where: { id: item.id } });
    expect(updated?.done).toBe(true);
  });
});
