"use server";

import { revalidatePath } from "next/cache";
import { BaseUnit } from "@prisma/client";
import { getScopedDb, assertCanWrite } from "@/server/tenant/context";
import { getPantryStock } from "@/server/queries/production";

export type ActionResult<T = undefined> = { ok: boolean; error?: string; data?: T };

function messageOf(e: unknown): string {
  return e instanceof Error ? e.message : "Algo deu errado.";
}

export async function generateAutoShoppingList(): Promise<
  ActionResult<{ created: number; updated: number }>
> {
  try {
    const { db, workspaceId } = await getScopedDb();
    await assertCanWrite();

    const stock = await getPantryStock();
    const belowMin = stock.filter((s) => s.belowMin && s.minStock != null);

    let created = 0;
    let updated = 0;

    for (const item of belowMin) {
      const deficit = Math.max(0, (item.minStock ?? 0) - item.current);
      const existing = await db.shoppingListItem.findFirst({
        where: {
          workspaceId,
          ingredientId: item.ingredientId,
          autoGenerated: true,
          done: false,
        },
      });

      if (existing) {
        await db.shoppingListItem.update({
          where: { id: existing.id },
          data: { quantity: deficit },
        });
        updated += 1;
        continue;
      }

      await db.shoppingListItem.create({
        data: {
          workspaceId,
          ingredientId: item.ingredientId,
          label: item.ingredientName,
          quantity: deficit,
          unit: item.baseUnit as BaseUnit,
          autoGenerated: true,
        },
      });
      created += 1;
    }

    revalidatePath("/pantry/shopping-list");
    return { ok: true, data: { created, updated } };
  } catch (e) {
    return { ok: false, error: messageOf(e) };
  }
}

export async function toggleShoppingListItem(id: string, done: boolean): Promise<ActionResult> {
  try {
    const { db, workspaceId } = await getScopedDb();
    await assertCanWrite();

    await db.shoppingListItem.updateMany({
      where: { id, workspaceId },
      data: { done },
    });

    revalidatePath("/pantry/shopping-list");
    return { ok: true };
  } catch (e) {
    return { ok: false, error: messageOf(e) };
  }
}
