BEGIN;

-- 1. Product vira a base física de Item
ALTER TABLE "product" RENAME TO "item";
ALTER TABLE "item" ADD COLUMN "unit" "BaseUnit" NOT NULL DEFAULT 'UN';
ALTER TABLE "item" ADD COLUMN "sellable" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "item" ADD COLUMN "productionInput" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "item" ADD COLUMN "minStock" DOUBLE PRECISION DEFAULT 0;

-- 2. Novo tipo de movimento de estoque
ALTER TYPE "StockMovementType" ADD VALUE 'CONSUMPTION';

-- 3. Insumos de revenda (Ingredient + Product pareado) se fundem no Item existente
UPDATE "item" i
SET "unit" = ing."baseUnit",
    "productionInput" = ing."isRawMaterial",
    "minStock" = ing."minStock"
FROM "ingredient" ing
WHERE ing."resaleProductId" = i.id
  AND ing."forResale" = true;

UPDATE "purchase_item" pi
SET "ingredientId" = ing."resaleProductId"
FROM "ingredient" ing
WHERE pi."ingredientId" = ing.id AND ing."forResale" = true AND ing."resaleProductId" IS NOT NULL;

UPDATE "recipe_ingredient" ri
SET "ingredientId" = ing."resaleProductId"
FROM "ingredient" ing
WHERE ri."ingredientId" = ing.id AND ing."forResale" = true AND ing."resaleProductId" IS NOT NULL;

UPDATE "shopping_list_item" sli
SET "ingredientId" = ing."resaleProductId"
FROM "ingredient" ing
WHERE sli."ingredientId" = ing.id AND ing."forResale" = true AND ing."resaleProductId" IS NOT NULL;

DELETE FROM "ingredient" WHERE "forResale" = true AND "resaleProductId" IS NOT NULL;

-- 4. Insumos puros (matéria-prima sem Product pareado) viram novas linhas de Item,
--    preservando o MESMO id (assim as colunas *_ingredient_id não precisam remapear valor, só nome)
INSERT INTO "item" (id, "workspaceId", name, active, "createdAt", "updatedAt", "unit", "sellable", "productionInput", "minStock")
SELECT id, "workspaceId", name, true, "createdAt", "updatedAt", "baseUnit", false, "isRawMaterial", "minStock"
FROM "ingredient";

ALTER TABLE "purchase_item" DROP CONSTRAINT "purchase_item_ingredientId_fkey";
ALTER TABLE "recipe_ingredient" DROP CONSTRAINT "recipe_ingredient_ingredientId_fkey";
ALTER TABLE "shopping_list_item" DROP CONSTRAINT "shopping_list_item_ingredientId_fkey";

DROP TABLE "ingredient";

-- 5. Renomeia colunas de FK nas tabelas dependentes
ALTER TABLE "purchase_item" RENAME COLUMN "ingredientId" TO "itemId";
ALTER TABLE "recipe_ingredient" RENAME COLUMN "ingredientId" TO "itemId";
ALTER TABLE "shopping_list_item" RENAME COLUMN "ingredientId" TO "itemId";
ALTER TABLE "sale_item" RENAME COLUMN "productId" TO "itemId";
ALTER TABLE "price_list_item" RENAME COLUMN "productId" TO "itemId";
ALTER TABLE "stock_movement" RENAME COLUMN "productId" TO "itemId";
ALTER TABLE "production_batch" RENAME COLUMN "productId" TO "itemId";
ALTER TABLE "flavor" RENAME COLUMN "productId" TO "itemId";

ALTER TABLE "purchase_item"
  ADD CONSTRAINT "purchase_item_itemId_fkey"
  FOREIGN KEY ("itemId") REFERENCES "item"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "recipe_ingredient"
  ADD CONSTRAINT "recipe_item_itemId_fkey"
  FOREIGN KEY ("itemId") REFERENCES "item"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "shopping_list_item"
  ADD CONSTRAINT "shopping_list_item_itemId_fkey"
  FOREIGN KEY ("itemId") REFERENCES "item"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- 6. Renomeações de tabela (Flavor -> Variant, RecipeIngredient -> RecipeItem, ProductionFilling -> ProductionVariantLine)
ALTER TABLE "flavor" RENAME TO "variant";
ALTER TABLE "variant" RENAME COLUMN "fillingRecipeId" TO "recipeId";
ALTER TABLE "recipe_ingredient" RENAME TO "recipe_item";
ALTER TABLE "production_filling" RENAME TO "production_variant_line";

-- 7. flavorId -> variantId em todas as tabelas que referenciam Variant
ALTER TABLE "production_variant_line" RENAME COLUMN "flavorId" TO "variantId";
ALTER TABLE "production_batch" RENAME COLUMN "flavorId" TO "variantId";
ALTER TABLE "sale_item" RENAME COLUMN "flavorId" TO "variantId";
ALTER TABLE "price_list_item" RENAME COLUMN "flavorId" TO "variantId";
ALTER TABLE "stock_movement" RENAME COLUMN "flavorId" TO "variantId";

-- 8. Lista de compras: campo autoGenerated sai do modelo (redesenho do fluxo, Task 11)
ALTER TABLE "shopping_list_item" DROP COLUMN "autoGenerated";

COMMIT;
